steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/runtime/c6-direct-trusted-runner/Dockerfile
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
